#!/bin/bash

ID=$(id -u)
TIMESTAMP=$(date +%F-%H-%M-%S)
R="\e[31m"
G="\e[32m"
N="\e[0m"

LOG_FILE="/tmp/$0-$TIMESTAMP.log"

#echo ("script started excecuted at $TIMESTAMP") &>> $LOG_FILE

VALIDATE()
{
if [ $1 -ne 0 ]
then

echo -e "installing  .. $2  is $R failed $N"
exit1

else

echo -e "installing ..$2  is $G success $N"
fi
}


if [ $ID -ne 0 ]
then
     echo "ERROR: please run with root user"
     exit 1
else
     echo "you are in root user"
fi

yum install mysql -y &>> $LOG_FILE

VALIDATE $? "MYSQL"

yum install git -y &>> $LOG_FILE

VALIDATE $? "GIT"





