#!/bin/bash

ID=$(id -u)
TIMESTAMP=$(date +%F-%H-%M-%S)
R="e[/31m"
G="e[/32m"
N="e[/0m"

VALIDATE()
{
if ($1 -ne 0)

echo "installing  .. $2  is $R failed $N"
exit1

else

echo "installing ..$2  is $G success $N"
fi
}

LOFILE="/tmp/$0-$TIMESTAMP.log"
echo "script started excecuted at $TIMESTAMP" &>>LOG_FILE


if ($ID -ne 0)

     echo (" $R ERROR :please run with root user $N")
     exit 1
else
     echo("user are in root user")
fi

yum install mysql -y $>>LOGFILE

VALIDATE $? "MYSQL"

yum install git -y $>>LOGFILE

VALIDATE $? "GIT"





